//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapSSO
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateResult", Namespace="SSO")]
    public partial class ValidateResult : object
    {
        
        private bool ValidateUserResultField;
        
        private string NIPField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ValidateUserResult
        {
            get
            {
                return this.ValidateUserResultField;
            }
            set
            {
                this.ValidateUserResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NIP
        {
            get
            {
                return this.NIPField;
            }
            set
            {
                this.NIPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="SSO", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SSO", ConfigurationName="SoapSSO.SSOWSSoap")]
    public interface SSOWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.ValidateUserResponse> ValidateUserAsync(SoapSSO.ValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ValidateUserGetNIP", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.ValidateUserGetNIPResponse> ValidateUserGetNIPAsync(SoapSSO.ValidateUserGetNIPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/Verify", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.VerifyResponse> VerifyAsync(SoapSSO.VerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnit", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetUserUnitResponse> GetUserUnitAsync(SoapSSO.GetUserUnitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetAllRolesResponse> GetAllRolesAsync(SoapSSO.GetAllRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetRolesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetRolesForUserResponse> GetRolesForUserAsync(SoapSSO.GetRolesForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUsersInRole", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetUsersInRoleResponse> GetUsersInRoleAsync(SoapSSO.GetUsersInRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/IsUserInRole", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.IsUserInRoleResponse> IsUserInRoleAsync(SoapSSO.IsUserInRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/RoleExists", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.RoleExistsResponse> RoleExistsAsync(SoapSSO.RoleExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/DeleteToken", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.DeleteTokenResponse> DeleteTokenAsync(SoapSSO.DeleteTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccessForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetAccessForUserResponse> GetAccessForUserAsync(SoapSSO.GetAccessForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.ChangePasswordResponse> ChangePasswordAsync(SoapSSO.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserType", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetUserTypeResponse> GetUserTypeAsync(SoapSSO.GetUserTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAllowModul", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetAllowModulResponse> GetAllowModulAsync(SoapSSO.GetAllowModulRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetAccesExtend", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetAccesExtendResponse> GetAccesExtendAsync(SoapSSO.GetAccesExtendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/CheckAccGroupUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.CheckAccGroupUserResponse> CheckAccGroupUserAsync(SoapSSO.CheckAccGroupUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SSO/GetUserUnitV2", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapSSO.GetUserUnitV2Response> GetUserUnitV2Async(SoapSSO.GetUserUnitV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUser", Namespace="SSO", Order=0)]
        public SoapSSO.ValidateUserRequestBody Body;
        
        public ValidateUserRequest()
        {
        }
        
        public ValidateUserRequest(SoapSSO.ValidateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserRequestBody()
        {
        }
        
        public ValidateUserRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserResponse", Namespace="SSO", Order=0)]
        public SoapSSO.ValidateUserResponseBody Body;
        
        public ValidateUserResponse()
        {
        }
        
        public ValidateUserResponse(SoapSSO.ValidateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponseBody()
        {
        }
        
        public ValidateUserResponseBody(bool ValidateUserResult)
        {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserGetNIPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserGetNIP", Namespace="SSO", Order=0)]
        public SoapSSO.ValidateUserGetNIPRequestBody Body;
        
        public ValidateUserGetNIPRequest()
        {
        }
        
        public ValidateUserGetNIPRequest(SoapSSO.ValidateUserGetNIPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserGetNIPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateUserGetNIPRequestBody()
        {
        }
        
        public ValidateUserGetNIPRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserGetNIPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserGetNIPResponse", Namespace="SSO", Order=0)]
        public SoapSSO.ValidateUserGetNIPResponseBody Body;
        
        public ValidateUserGetNIPResponse()
        {
        }
        
        public ValidateUserGetNIPResponse(SoapSSO.ValidateUserGetNIPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ValidateUserGetNIPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapSSO.ValidateResult ValidateUserGetNIPResult;
        
        public ValidateUserGetNIPResponseBody()
        {
        }
        
        public ValidateUserGetNIPResponseBody(SoapSSO.ValidateResult ValidateUserGetNIPResult)
        {
            this.ValidateUserGetNIPResult = ValidateUserGetNIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Verify", Namespace="SSO", Order=0)]
        public SoapSSO.VerifyRequestBody Body;
        
        public VerifyRequest()
        {
        }
        
        public VerifyRequest(SoapSSO.VerifyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class VerifyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public VerifyRequestBody()
        {
        }
        
        public VerifyRequestBody(string username, string token)
        {
            this.username = username;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyResponse", Namespace="SSO", Order=0)]
        public SoapSSO.VerifyResponseBody Body;
        
        public VerifyResponse()
        {
        }
        
        public VerifyResponse(SoapSSO.VerifyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class VerifyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyResult;
        
        public VerifyResponseBody()
        {
        }
        
        public VerifyResponseBody(bool VerifyResult)
        {
            this.VerifyResult = VerifyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnit", Namespace="SSO", Order=0)]
        public SoapSSO.GetUserUnitRequestBody Body;
        
        public GetUserUnitRequest()
        {
        }
        
        public GetUserUnitRequest(SoapSSO.GetUserUnitRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserUnitRequestBody()
        {
        }
        
        public GetUserUnitRequestBody(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetUserUnitResponseBody Body;
        
        public GetUserUnitResponse()
        {
        }
        
        public GetUserUnitResponse(SoapSSO.GetUserUnitResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserUnitResult;
        
        public GetUserUnitResponseBody()
        {
        }
        
        public GetUserUnitResponseBody(string GetUserUnitResult)
        {
            this.GetUserUnitResult = GetUserUnitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoles", Namespace="SSO", Order=0)]
        public SoapSSO.GetAllRolesRequestBody Body;
        
        public GetAllRolesRequest()
        {
        }
        
        public GetAllRolesRequest(SoapSSO.GetAllRolesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllRolesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        public GetAllRolesRequestBody()
        {
        }
        
        public GetAllRolesRequestBody(string appName)
        {
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRolesResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetAllRolesResponseBody Body;
        
        public GetAllRolesResponse()
        {
        }
        
        public GetAllRolesResponse(SoapSSO.GetAllRolesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllRolesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapSSO.ArrayOfString GetAllRolesResult;
        
        public GetAllRolesResponseBody()
        {
        }
        
        public GetAllRolesResponseBody(SoapSSO.ArrayOfString GetAllRolesResult)
        {
            this.GetAllRolesResult = GetAllRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUser", Namespace="SSO", Order=0)]
        public SoapSSO.GetRolesForUserRequestBody Body;
        
        public GetRolesForUserRequest()
        {
        }
        
        public GetRolesForUserRequest(SoapSSO.GetRolesForUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetRolesForUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        public GetRolesForUserRequestBody()
        {
        }
        
        public GetRolesForUserRequestBody(string username, string appName)
        {
            this.username = username;
            this.appName = appName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUserResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetRolesForUserResponseBody Body;
        
        public GetRolesForUserResponse()
        {
        }
        
        public GetRolesForUserResponse(SoapSSO.GetRolesForUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetRolesForUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapSSO.ArrayOfString GetRolesForUserResult;
        
        public GetRolesForUserResponseBody()
        {
        }
        
        public GetRolesForUserResponseBody(SoapSSO.ArrayOfString GetRolesForUserResult)
        {
            this.GetRolesForUserResult = GetRolesForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersInRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersInRole", Namespace="SSO", Order=0)]
        public SoapSSO.GetUsersInRoleRequestBody Body;
        
        public GetUsersInRoleRequest()
        {
        }
        
        public GetUsersInRoleRequest(SoapSSO.GetUsersInRoleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUsersInRoleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleName;
        
        public GetUsersInRoleRequestBody()
        {
        }
        
        public GetUsersInRoleRequestBody(string appName, string roleName)
        {
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersInRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersInRoleResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetUsersInRoleResponseBody Body;
        
        public GetUsersInRoleResponse()
        {
        }
        
        public GetUsersInRoleResponse(SoapSSO.GetUsersInRoleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUsersInRoleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoapSSO.ArrayOfString GetUsersInRoleResult;
        
        public GetUsersInRoleResponseBody()
        {
        }
        
        public GetUsersInRoleResponseBody(SoapSSO.ArrayOfString GetUsersInRoleResult)
        {
            this.GetUsersInRoleResult = GetUsersInRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserInRoleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserInRole", Namespace="SSO", Order=0)]
        public SoapSSO.IsUserInRoleRequestBody Body;
        
        public IsUserInRoleRequest()
        {
        }
        
        public IsUserInRoleRequest(SoapSSO.IsUserInRoleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class IsUserInRoleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string roleName;
        
        public IsUserInRoleRequestBody()
        {
        }
        
        public IsUserInRoleRequestBody(string username, string appName, string roleName)
        {
            this.username = username;
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserInRoleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserInRoleResponse", Namespace="SSO", Order=0)]
        public SoapSSO.IsUserInRoleResponseBody Body;
        
        public IsUserInRoleResponse()
        {
        }
        
        public IsUserInRoleResponse(SoapSSO.IsUserInRoleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class IsUserInRoleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUserInRoleResult;
        
        public IsUserInRoleResponseBody()
        {
        }
        
        public IsUserInRoleResponseBody(bool IsUserInRoleResult)
        {
            this.IsUserInRoleResult = IsUserInRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoleExistsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoleExists", Namespace="SSO", Order=0)]
        public SoapSSO.RoleExistsRequestBody Body;
        
        public RoleExistsRequest()
        {
        }
        
        public RoleExistsRequest(SoapSSO.RoleExistsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class RoleExistsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleName;
        
        public RoleExistsRequestBody()
        {
        }
        
        public RoleExistsRequestBody(string appName, string roleName)
        {
            this.appName = appName;
            this.roleName = roleName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RoleExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RoleExistsResponse", Namespace="SSO", Order=0)]
        public SoapSSO.RoleExistsResponseBody Body;
        
        public RoleExistsResponse()
        {
        }
        
        public RoleExistsResponse(SoapSSO.RoleExistsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class RoleExistsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RoleExistsResult;
        
        public RoleExistsResponseBody()
        {
        }
        
        public RoleExistsResponseBody(bool RoleExistsResult)
        {
            this.RoleExistsResult = RoleExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteToken", Namespace="SSO", Order=0)]
        public SoapSSO.DeleteTokenRequestBody Body;
        
        public DeleteTokenRequest()
        {
        }
        
        public DeleteTokenRequest(SoapSSO.DeleteTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class DeleteTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public DeleteTokenRequestBody()
        {
        }
        
        public DeleteTokenRequestBody(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteTokenResponse", Namespace="SSO", Order=0)]
        public SoapSSO.DeleteTokenResponseBody Body;
        
        public DeleteTokenResponse()
        {
        }
        
        public DeleteTokenResponse(SoapSSO.DeleteTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteTokenResponseBody
    {
        
        public DeleteTokenResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessForUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessForUser", Namespace="SSO", Order=0)]
        public SoapSSO.GetAccessForUserRequestBody Body;
        
        public GetAccessForUserRequest()
        {
        }
        
        public GetAccessForUserRequest(SoapSSO.GetAccessForUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccessForUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string formName;
        
        public GetAccessForUserRequestBody()
        {
        }
        
        public GetAccessForUserRequestBody(string username, string appName, string formName)
        {
            this.username = username;
            this.appName = appName;
            this.formName = formName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessForUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessForUserResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetAccessForUserResponseBody Body;
        
        public GetAccessForUserResponse()
        {
        }
        
        public GetAccessForUserResponse(SoapSSO.GetAccessForUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccessForUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessForUserResult;
        
        public GetAccessForUserResponseBody()
        {
        }
        
        public GetAccessForUserResponseBody(string GetAccessForUserResult)
        {
            this.GetAccessForUserResult = GetAccessForUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="SSO", Order=0)]
        public SoapSSO.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest()
        {
        }
        
        public ChangePasswordRequest(SoapSSO.ChangePasswordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ChangePasswordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OdlPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NewPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserId;
        
        public ChangePasswordRequestBody()
        {
        }
        
        public ChangePasswordRequestBody(string OdlPass, string NewPass, string UserId)
        {
            this.OdlPass = OdlPass;
            this.NewPass = NewPass;
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="SSO", Order=0)]
        public SoapSSO.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse()
        {
        }
        
        public ChangePasswordResponse(SoapSSO.ChangePasswordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class ChangePasswordResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody()
        {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult)
        {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTypeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserType", Namespace="SSO", Order=0)]
        public SoapSSO.GetUserTypeRequestBody Body;
        
        public GetUserTypeRequest()
        {
        }
        
        public GetUserTypeRequest(SoapSSO.GetUserTypeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserTypeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        public GetUserTypeRequestBody()
        {
        }
        
        public GetUserTypeRequestBody(string userid)
        {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserTypeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserTypeResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetUserTypeResponseBody Body;
        
        public GetUserTypeResponse()
        {
        }
        
        public GetUserTypeResponse(SoapSSO.GetUserTypeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserTypeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserTypeResult;
        
        public GetUserTypeResponseBody()
        {
        }
        
        public GetUserTypeResponseBody(string GetUserTypeResult)
        {
            this.GetUserTypeResult = GetUserTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllowModulRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllowModul", Namespace="SSO", Order=0)]
        public SoapSSO.GetAllowModulRequestBody Body;
        
        public GetAllowModulRequest()
        {
        }
        
        public GetAllowModulRequest(SoapSSO.GetAllowModulRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllowModulRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Modul;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Access;
        
        public GetAllowModulRequestBody()
        {
        }
        
        public GetAllowModulRequestBody(string UserId, string Modul, int Access)
        {
            this.UserId = UserId;
            this.Modul = Modul;
            this.Access = Access;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllowModulResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllowModulResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetAllowModulResponseBody Body;
        
        public GetAllowModulResponse()
        {
        }
        
        public GetAllowModulResponse(SoapSSO.GetAllowModulResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAllowModulResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetAllowModulResult;
        
        public GetAllowModulResponseBody()
        {
        }
        
        public GetAllowModulResponseBody(bool GetAllowModulResult)
        {
            this.GetAllowModulResult = GetAllowModulResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccesExtendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccesExtend", Namespace="SSO", Order=0)]
        public SoapSSO.GetAccesExtendRequestBody Body;
        
        public GetAccesExtendRequest()
        {
        }
        
        public GetAccesExtendRequest(SoapSSO.GetAccesExtendRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccesExtendRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Extid;
        
        public GetAccesExtendRequestBody()
        {
        }
        
        public GetAccesExtendRequestBody(string UserId, int Extid)
        {
            this.UserId = UserId;
            this.Extid = Extid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccesExtendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccesExtendResponse", Namespace="SSO", Order=0)]
        public SoapSSO.GetAccesExtendResponseBody Body;
        
        public GetAccesExtendResponse()
        {
        }
        
        public GetAccesExtendResponse(SoapSSO.GetAccesExtendResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetAccesExtendResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetAccesExtendResult;
        
        public GetAccesExtendResponseBody()
        {
        }
        
        public GetAccesExtendResponseBody(bool GetAccesExtendResult)
        {
            this.GetAccesExtendResult = GetAccesExtendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccGroupUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccGroupUser", Namespace="SSO", Order=0)]
        public SoapSSO.CheckAccGroupUserRequestBody Body;
        
        public CheckAccGroupUserRequest()
        {
        }
        
        public CheckAccGroupUserRequest(SoapSSO.CheckAccGroupUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CheckAccGroupUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccGroup;
        
        public CheckAccGroupUserRequestBody()
        {
        }
        
        public CheckAccGroupUserRequestBody(string UserId, string AccGroup)
        {
            this.UserId = UserId;
            this.AccGroup = AccGroup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAccGroupUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAccGroupUserResponse", Namespace="SSO", Order=0)]
        public SoapSSO.CheckAccGroupUserResponseBody Body;
        
        public CheckAccGroupUserResponse()
        {
        }
        
        public CheckAccGroupUserResponse(SoapSSO.CheckAccGroupUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class CheckAccGroupUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckAccGroupUserResult;
        
        public CheckAccGroupUserResponseBody()
        {
        }
        
        public CheckAccGroupUserResponseBody(bool CheckAccGroupUserResult)
        {
            this.CheckAccGroupUserResult = CheckAccGroupUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitV2", Namespace="SSO", Order=0)]
        public SoapSSO.GetUserUnitV2RequestBody Body;
        
        public GetUserUnitV2Request()
        {
        }
        
        public GetUserUnitV2Request(SoapSSO.GetUserUnitV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserUnitV2RequestBody()
        {
        }
        
        public GetUserUnitV2RequestBody(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserUnitV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserUnitV2Response", Namespace="SSO", Order=0)]
        public SoapSSO.GetUserUnitV2ResponseBody Body;
        
        public GetUserUnitV2Response()
        {
        }
        
        public GetUserUnitV2Response(SoapSSO.GetUserUnitV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="SSO")]
    public partial class GetUserUnitV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserUnitV2Result;
        
        public GetUserUnitV2ResponseBody()
        {
        }
        
        public GetUserUnitV2ResponseBody(string GetUserUnitV2Result)
        {
            this.GetUserUnitV2Result = GetUserUnitV2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SSOWSSoapChannel : SoapSSO.SSOWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SSOWSSoapClient : System.ServiceModel.ClientBase<SoapSSO.SSOWSSoap>, SoapSSO.SSOWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SSOWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(SSOWSSoapClient.GetBindingForEndpoint(endpointConfiguration), SSOWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SSOWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SSOWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SSOWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SoapSSO.ValidateUserResponse> ValidateUserAsync(SoapSSO.ValidateUserRequest request)
        {
            return base.Channel.ValidateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.ValidateUserGetNIPResponse> ValidateUserGetNIPAsync(SoapSSO.ValidateUserGetNIPRequest request)
        {
            return base.Channel.ValidateUserGetNIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.VerifyResponse> VerifyAsync(SoapSSO.VerifyRequest request)
        {
            return base.Channel.VerifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetUserUnitResponse> GetUserUnitAsync(SoapSSO.GetUserUnitRequest request)
        {
            return base.Channel.GetUserUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetAllRolesResponse> GetAllRolesAsync(SoapSSO.GetAllRolesRequest request)
        {
            return base.Channel.GetAllRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetRolesForUserResponse> GetRolesForUserAsync(SoapSSO.GetRolesForUserRequest request)
        {
            return base.Channel.GetRolesForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetUsersInRoleResponse> GetUsersInRoleAsync(SoapSSO.GetUsersInRoleRequest request)
        {
            return base.Channel.GetUsersInRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.IsUserInRoleResponse> IsUserInRoleAsync(SoapSSO.IsUserInRoleRequest request)
        {
            return base.Channel.IsUserInRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.RoleExistsResponse> RoleExistsAsync(SoapSSO.RoleExistsRequest request)
        {
            return base.Channel.RoleExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.DeleteTokenResponse> DeleteTokenAsync(SoapSSO.DeleteTokenRequest request)
        {
            return base.Channel.DeleteTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetAccessForUserResponse> GetAccessForUserAsync(SoapSSO.GetAccessForUserRequest request)
        {
            return base.Channel.GetAccessForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.ChangePasswordResponse> ChangePasswordAsync(SoapSSO.ChangePasswordRequest request)
        {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetUserTypeResponse> GetUserTypeAsync(SoapSSO.GetUserTypeRequest request)
        {
            return base.Channel.GetUserTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetAllowModulResponse> GetAllowModulAsync(SoapSSO.GetAllowModulRequest request)
        {
            return base.Channel.GetAllowModulAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetAccesExtendResponse> GetAccesExtendAsync(SoapSSO.GetAccesExtendRequest request)
        {
            return base.Channel.GetAccesExtendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.CheckAccGroupUserResponse> CheckAccGroupUserAsync(SoapSSO.CheckAccGroupUserRequest request)
        {
            return base.Channel.CheckAccGroupUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapSSO.GetUserUnitV2Response> GetUserUnitV2Async(SoapSSO.GetUserUnitV2Request request)
        {
            return base.Channel.GetUserUnitV2Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap))
            {
                //return new System.ServiceModel.EndpointAddress("http://ptprkpapp04.ptpr.com:8092/SSOWS.asmx");
                return new System.ServiceModel.EndpointAddress("http://sso.pertaminaretail.com/SSOWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.SSOWSSoap12))
            {
                //return new System.ServiceModel.EndpointAddress("http://ptprkpapp04.ptpr.com:8092/SSOWS.asmx");
                return new System.ServiceModel.EndpointAddress("http://sso.pertaminaretail.com/SSOWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            SSOWSSoap,
            
            SSOWSSoap12,
        }
    }
}
